# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20170807_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restuarantlocation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
