# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20170807_1752'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestuarantLocation',
            new_name='RestaurantLocation',
        ),
    ]
